services:
  bot:
    build: .
    container_name: chatbot-app
    volumes:
      - .:/app
    ports:
      - "8070:8070"
    restart: unless-stopped
    networks:
      - chatbot_net

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      - bot
    networks:
      - chatbot_net


volumes:
  chatbot_cache:

networks:
  chatbot_net:
